# Generated by Django 6.0.6 on 2026-07-07 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='client/profiles/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=20)),
                ('fitness_goal', models.CharField(blank=True, choices=[('LOSE_WEIGHT', 'Lose Weight'), ('BUILD_MUSCLE', 'Build Muscle'), ('IMPROVE_ENDURANCE', 'Improve Endurance'), ('INCREASE_FLEXIBILITY', 'Increase Flexibility'), ('MAINTAIN_FITNESS', 'Maintain Fitness'), ('GENERAL_HEALTH', 'General Health')], max_length=30)),
                ('preferred_workout', models.CharField(blank=True, choices=[('STRENGTH_TRAINING', 'Strength Training'), ('CARDIO', 'Cardio'), ('YOGA', 'Yoga'), ('HIIT', 'HIIT'), ('PILATES', 'Pilates'), ('CROSSFIT', 'CrossFit'), ('SWIMMING', 'Swimming'), ('CYCLING', 'Cycling')], max_length=30)),
                ('experience_level', models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimetres', max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Current weight in kilograms', max_digits=5, null=True)),
                ('target_weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Target weight in kilograms', max_digits=5, null=True)),
                ('diet_preference', models.CharField(blank=True, choices=[('NONE', 'No Preference'), ('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('KETO', 'Keto'), ('PALEO', 'Paleo'), ('GLUTEN_FREE', 'Gluten-Free'), ('DAIRY_FREE', 'Dairy-Free')], default='NONE', max_length=20)),
                ('medical_condition', models.TextField(blank=True, help_text='Any medical conditions or injuries the trainer should know about')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
